require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

LiteralInInterpolation:
  Exclude:
    - 'spec/**/*'

Style/SignalException:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/SubjectStub:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  MaxNesting: 3
