require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Style/SignalException:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/SubjectStub:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
